name: Deploy Website

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    env:
      IMAGE_NAME: rg.fr-par.scw.cloud/console-scw/scaleway-ui-website
      DEPLOYMENT_NAME: 'website'

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Cache Docker layers
        uses: actions/cache@v3.3.1
        with:
          path: /tmp/website/.buildx-cache
          key: ${{ runner.os }}-buildx
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Export custom variables
        run: |
          SAFE_GITHUB_HEAD_REF_SLUG_URL=$(echo $GITHUB_HEAD_REF_SLUG_URL-$DEPLOYMENT_NAME | rev | cut -c-37 | rev | sed 's/^-//g')
          ([[ $GITHUB_REF == 'refs/heads/main' ]] && echo "BRANCH_SLUG=main" || echo "BRANCH_SLUG=$SAFE_GITHUB_HEAD_REF_SLUG_URL") >> $GITHUB_ENV

      - name: Start deployment
        uses: bobheadxi/deployments@v1.4.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.GH_TOKEN }}
          env: ${{ env.BRANCH_SLUG }}
          ref: ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Login to Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: rg.fr-par.scw.cloud/console-scw
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      - name: Build
        uses: docker/build-push-action@v4.0.0
        env:
          IMAGE: ${{ env.IMAGE_NAME }}:${{ env.BRANCH_SLUG }}
        with:
          push: true
          tags: ${{ env.IMAGE }}
          file: Dockerfile.website
          cache-from: type=local,src=/tmp/website/.buildx-cache
          cache-to: type=local,dest=/tmp/website/.buildx-cache-new,mode=max

      - name: Deploy Serverless Container Scaleway
        uses: philibea/scaleway-containers-deploy@v1.0.8
        id: deploy
        with:
          type: 'deploy'
          scw_dns: ${{ secrets.SCW_DNS }}
          root_zone: ${{ env.BRANCH_SLUG == 'main' }}
          scw_access_key: ${{ secrets.SCW_ACCESS_KEY }}
          scw_secret_key: ${{ secrets.SCW_SECRET_KEY }}
          scw_containers_namespace_id: ${{ secrets.SCW_CONTAINERS_WEBSITE_NAMESPACE_ID }}
          scw_registry: ${{ env.IMAGE_NAME }}:${{ env.BRANCH_SLUG }}

      - name: Update deployment status
        uses: bobheadxi/deployments@v1.4.0
        if: always()
        with:
          step: finish
          env: ${{ env.BRANCH_SLUG }}
          token: ${{ secrets.GH_TOKEN }}
          auto_inactive: true
          # This will now be automatically handled by github with the auto_inactive
          override: false
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: ${{ steps.deploy.outputs.url }}

      - name: Move cache
        run: |
          rm -rf /tmp/website/.buildx-cache
          mv /tmp/website/.buildx-cache-new /tmp/website/.buildx-cache
