name: Upload Fonts

on:
  push:
    branches:
      - "main"
    # to test
    pull_request:
      types: ["opened", "edited", "reopened", "synchronize"]
    paths:
      - packages/fonts/**
env:
  BUCKET_NAME: scaleway-assets
  BUCKET_REGION: fr-par

jobs:
  ## Synchronize assets on bucket
  upload-fonts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.SCALEWAY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SCALEWAY_SECRET_KEY }}
          aws-region: ${{ env.BUCKET_REGION }}

      - name: AWS CLI configuration
        run: |
          mkdir ~/.aws
          cp ./.aws/* ~/.aws/
          sed -i -e 's/${BUCKET_REGION}/${{env.BUCKET_REGION}}/g' ~/.aws/config

      - name: Upload fonts on bucket
        run: |
          aws s3 sync packages/fonts/src/assets s3://${{ env.BUCKET_NAME }}/fonts/ --endpoint-url=https://s3.${{ env.BUCKET_REGION }}.scw.cloud --include "*" --acl public-read --cache-control max-age=2592000,public
          aws s3api put-bucket-cors --bucket ${{ env.BUCKET_NAME }} --cors-configuration file://.aws/cors.json --endpoint-url=https://s3.${{ env.BUCKET_REGION }}.scw.cloud
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
