name: Upload Fonts

on:
  push:
    branches:
      - "main"
    paths:
      - packages/fonts/**
env:
  BUCKET_NAME: scaleway-assets
  BUCKET_REGION: fr-par

jobs:
  ## Synchronize assets on bucket
  upload-fonts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2 # default
          verbose: false

      - name: AWS CLI configuration
        run: |
          mkdir ~/.aws
          cp ./.aws/* ~/.aws/
          sed -i -e 's/${BUCKET_REGION}/${{env.BUCKET_REGION}}/g' ~/.aws/config

      - run: aws configure list
        shell: bash

      - name: Upload fonts on bucket
        run: |
          aws s3 sync packages/fonts/src/assets s3://${{ env.BUCKET_NAME }}/fonts/  --include "*" --acl public-read --cache-control max-age=2592000,public --endpoint-url=https://s3.${{ env.BUCKET_REGION }}.scw.cloud
          aws s3api put-bucket-cors --bucket ${{ env.BUCKET_NAME }} --cors-configuration file://.aws/cors.json --endpoint-url=https://s3.${{ env.BUCKET_REGION }}.scw.cloud
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
