name: Visual

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  build-storybook:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17
      - run: yarn install
      - run: yarn run build:storybook-visual
      - uses: actions/cache@v2
        id: restore-build-visual
        with:
          path: ./*
          key: ${{ github.sha }}
  visual:
    needs: [build-storybook]
    strategy:
      matrix:
        filter: ["[A-C]", "D", "[E-Z]"]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Use Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 17
          cache: "yarn"
      - run: yarn install
      - uses: actions/cache@v2
        id: restore-build-visual
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: yarn run test:visual --storiesFilter ^Components/${{ matrix.filter }}
      - name: Archive screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: storybook-screenshots
          path: .loki/difference
          retention-days: 5
